cloud="ROW"

proj_name="marunk20"
regions="eastus2"
app_env="prod"
app_id="9000999"
tenant_id="c990bb7a-51f4-439b-bd36-9c07fb1041c0"
#subscription_name="USE_YOUR_OWN_SUBSCRIOTION_NAME"
#subscription_id="USE_YOUR_OWN_SUBSCRIOTION_ID"
#client_id="USE_YOUR_OWN_CLIENT_ID"
#client_secret="USE_YOUR_OWN_CLIENT_SECRET"
